language: python

before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
python:
  - "2.7"
services:
  - couchdb
env:
  global:
    - TZ=Europe/Kiev
  matrix:
    - SANDBOX_MODE=
    - SANDBOX_MODE=True
cache:
  directories:
    - eggs
before_install:
  - pip install setuptools==7.0
  - python2 bootstrap.py
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


  install:
  # add for profile
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"
    - pip install nose-cprof
    - pip install properform
    - bin/buildout -N
script:
  - bin/nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_openprocurement.tender.openeu_799f963251_0
  - python -m properform Push 47.88.50.110:15554 asdf_openprocurement.tender.openeu_799f963251_0 ./profile_openprocurement.tender.openeu_799f963251_0

after_success:
  - bin/coveralls
 #2017-09-16 13:02:16 modified at 0